#A Deployment provides declarative updates for Pods and ReplicaSets.
#You can define Deployments to create new ReplicaSets, or to remove existing Deployments
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  #thus labels are deployment related labels
  labels:
    app: nginx
    purpose: HELM
spec:
  replicas: {{ .Values.deployment.replicas }} #refers values inside values.yaml 
  selector: 
    matchLabels:
      app: nginx
      purpose: HELM
  #pod defintion
  template:
    metadata:
      labels:
        app: nginx
        purpose: HELM
    spec:
    - name: nginx
      image: nginx