# This service is used to call nginx Pod
apiVersion: v1
kind: Service
metadata: 
  name: nginx
spec: 
  selectors:
    app: nginx
    purpose: HELM
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    