# This service is used to call mysql Pods
apiVersion: v1
kind: Service
metadata: 
  name: mysql
  #attaching to expense namespace
  namespace: expense
spec: 
  selectors:
    project: expense
    component: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    