kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  #creating mysql in expense namespace
  namespace: expense
  #thus labels are deployment related labels
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector: 
    matchLabels:
      component: backend
      tier: app
      project: expense
  #pod defintion
  template:
    metadata:
      labels:
        component: backend
        tier: app
        project: expense
    spec:
    - name: backend
      image: guru1188/backend:v1.0
      envFrom:
      - configMapRef:
          name: backend
