# This service is used to call baclemd Pod, by using selectors of backend
apiVersion: v1
kind: Service
metadata: 
  name: backend
  #attaching to expense namespace
  namespace: expense
spec: 
  selectors:
    project: expense
    component: backend
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080